### ISSUE TITLE
Node::RegisterResponse::operator(): Error in onRegisterFailed

### ISSUE THREAD

**Issue by yoursunny** [operantnetworks/ndn-ind#23]
Environment:

* Ubuntu 18.04
* ndn-ind commit dd934a7a5106cda6ea14675554427e12df1ce18f
* [DNMP-v2](https://github.com/pollere/DNMP-v2) (an app using ndn-ind library) commit c9431460f85c326a410758aa4ff2a26bfcf0df69
* `liblog4cxx-dev libprotobuf-dev protobuf-compiler` are installed before compiling ndn-ind
* Compiler: `clang++-8`
* NFD 0.7.1 installed from PPA, unpatched

When I attempt to launch any program (e.g. `./nod`), there's an error message:

```
16:34:06 ERROR SyncPubsub - onRegisterFailed /localhost/dnmp
16:34:06 ERROR Node - Node::RegisterResponse::operator(): Error in onRegisterFailed: onRegisterFailed /localhost/dnmp
16:34:06 ERROR SyncPubsub - onRegisterFailed /localnet/dnmp/all
16:34:06 ERROR Node - Node::RegisterResponse::operator(): Error in onRegisterFailed: onRegisterFailed /localnet/dnmp/all
16:34:06 ERROR SyncPubsub - onRegisterFailed /localnet/dnmp/pid869_sunny5
16:34:06 ERROR Node - Node::RegisterResponse::operator(): Error in onRegisterFailed: onRegisterFailed /localnet/dnmp/pid869_sunny5
```

NFD log says:

```
1609364044.155467  WARN: [nfd.GenericLinkService] [id=259,local=unix:///run/nfd.sock,remote=fd://25] packet parse error (Unrecognized element of critical type 9): DROP
1609364044.155525  WARN: [nfd.GenericLinkService] [id=259,local=unix:///run/nfd.sock,remote=fd://25] packet parse error (Unrecognized element of critical type 9): DROP
1609364044.155552  WARN: [nfd.GenericLinkService] [id=259,local=unix:///run/nfd.sock,remote=fd://25] packet parse error (Unrecognized element of critical type 9): DROP
```

TLV-TYPE 0x09 is the assignment of `Selectors` field that belongs to an obsolete packet format no longer supported by NFD.

To solve this problem, ndn-ind should encode as NDN Packet Format 0.3 by default.

Originally reported on https://github.com/pollere/DNMP-v2/issues/4 
CC @kmnichols

**Comment by jefft0** [comment]
Pull request #24 is merged.
